project:
  type: website

website:
  title: "MMMOO Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: organizers.qmd
        text: Organizers
  page-footer:
    center: |
      Created with ♥ by Lennart Schäpermeier using [Quarto](https://quarto.org).  
      Hosted using [GitHub Pages](https://pages.github.com).
  
  margin-footer: margin.qmd

fig-align: left

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
