---
title: "MMMOO Workshop @ PPSN 2024"
tbl-cap-location: top
toc: false
---

In our workshop on multimodal multi-objective optimization (**MMMOO Workshop**), we will discuss properties and challenges, but also opportunities, of multimodality in multi-objective optimization.
The workshop is organized jointly by **Heike Trautmann**, **Oliver Schütze** and **Lennart Schäpermeier** at the [PPSN 2024 conference](https://ppsn2024.fh-ooe.at).
It is scheduled for Sunday, September 15th 1:30PM – 5:00PM.

Learn more about the [goals of this workshop](./about.qmd) and about the [organizers](organizers.qmd).

## Schedule

Below, you find the preliminary schedule for the workshop.
We start with three overview talks in the first part of the workshop.
After a short break, we'll follow up with a few shorter talks on recent research projects.
Finally, we want to bring everyone together in an open discussion on commonalities, differences, and future potentials of MMMOO research.

|  Time |  Speaker |  Title |
|-------|----------|--------|
| **Overview Talks** | | |
| 1:30PM - 1:50PM | Lennart Schäpermeier | Overview of Continuous Multimodal Multi-objective Optimization |
| 1:50PM - 2:00PM |   | Discussion |
| 2:00PM - 2:20PM | Ofer Shir | Overcoming Coupon Collector's Syndrome on Multimodal Domains |
| 2:20PM - 2:30PM |   | Discussion |
| 2:30PM - 2:50PM | Arnaud Liefooghe (remote) | Insights into the Multimodality of Multi-Objective Combinatorial Landscapes |
| 2:50PM - 3:00PM |   | Discussion |
| **Break** (3:00PM - 3:30PM) |
| **Combinatorial Domain** |
| 3:30PM - 3:40PM | Oliver Preuss | On the Dominance of Omni-Optimizer in MNK-Landscapes |
| 3:40PM - 3:50PM | Gabriela Ochoa | Multi-objective trajectories and landscapes: a complex networks view |
| **Continuous Domain** |
| 3:50PM - 4:00PM | Oliver Schütze | Nearly optimal solutions in the context of multimodal multi-objective optimization |
| 4:00PM - 4:10PM | Urban Skvorc | Behaviour of (1+1) and (5+1) EA on Multimodal MO Landscapes |
| 4:10PM - 4:20PM | Hisao Ishibuchi | How to choose a set of well-distributed solutions in both the decision and objective spaces |
| 4:20PM - 4:30PM | Miqing Li | Visualising the Landscape of (Multimodal) Multiobjective Optimisation Problems |
| 4:30PM - 5:00PM |   | Discussion |

: {tbl-colwidths="[30,25,45]"}
